# FFNx Audio Engine config file - Voice layer

### HOW TO: ###################################################################
# Sections may be commented by default with an initial # character.
# Remove the initial # character to set the entire sections block and its flags
# -----------------------------------------------------------------------------
# Syntax:
# [FIELDNAME/FILENAME]
# flag = value
# another_flag = value
# -----------------------------------------------------------------------------
# where:
# - FIELDNAME: the current field name, for eg. 'md1stin'
# - FILENAME: the filename as you have it in your own folder,
#             for eg. '6' for 6.ogg
###############################################################################

### SUPPORTED FLAGS: ##########################################################
# volume: Allow volume to be adjusted for a specific track.
###############################################################################

# This entry will set the volume to 50%
# -----------------------------------------------------------------------------
#[md1stin/6]
#volume = 50
